name: build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@3ebd1aebb47f95493b62de6eec0cac3cd74e50a9
        with:
          diagnostic-endpoint:
      - uses: DeterminateSystems/magic-nix-cache-action@749fc5bbc9fa49d60c2b93f6c4bc867b82e1d295
        with:
          diagnostic-endpoint:
      - name: Build binary
        run: |
          nix build --print-build-logs
      - name: Build docker image
        run: |
          nix build .#gotchet-docker --print-build-logs
          podman load -i ./result
