name: build
on: [pull_request, push]
env:
  DOCKER_REPO: docker.io/alexanderbakker/gotchet
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@de22e16c4711fca50c816cc9081563429d1cf563
        with:
          diagnostic-endpoint:
      - uses: DeterminateSystems/magic-nix-cache-action@fc6aaceb40b9845a02b91e059ec147e78d1b4e41
        with:
          diagnostic-endpoint:
      - name: Build binary
        run: |
          nix build --print-build-logs
          ./result/bin/gotchet version
      - name: Check version number
        if: startsWith(github.ref_name, 'v')
        run: |
          if ! ./result/bin/gotchet version | grep -q '${{ github.ref_name }}'; then
            echo "Version information doesn't match"
            exit 1
          fi
      - name: Build docker image
        run: |
          nix build .#gotchet-docker --print-build-logs
          podman load -i ./result
      - name: Tag Docker image
        id: tag
        if: startsWith(github.ref_name, 'v')
        run: |
          tag=$(echo "${{github.ref_name}}" | cut -c2-)
          podman tag localhost/gotchet:latest $DOCKER_REPO:latest
          podman tag localhost/gotchet:latest $DOCKER_REPO:${tag}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
      - name: Log into Docker Hub
        if: startsWith(github.ref_name, 'v')
        uses: redhat-actions/podman-login@4934294ad0449894bcd1e9f191899d7292469603
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Push to Docker Hub
        if: startsWith(github.ref_name, 'v')
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c
        with:
          tags: ${{ env.DOCKER_REPO }}:latest ${{ env.DOCKER_REPO }}:${{ steps.tag.outputs.tag }}
